# Generated by Django 5.1.7 on 2025-05-27 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password_hash',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='points',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='salt',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='xp',
        ),
    ]
