# Generated by Django 5.1.7 on 2025-05-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskfile',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
