# Generated by Django 5.1.7 on 2025-06-05 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userbadge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBadge',
        ),
    ]
