# Generated by Django 5.1.7 on 2025-06-05 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_internalreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internalreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Internal Report', 'verbose_name_plural': 'Internal Reports'},
        ),
    ]
