# Generated by Django 5.1.7 on 2025-06-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_quiz_quizquestion_quizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='points_reward',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='xp_reward',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
